# monitoring/prometheus-rules.yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: orchestrator-rules
  namespace: orchestrator-system
spec:
  groups:
  - name: orchestrator.rules
    rules:
    - alert: OrchestratorDown
      expr: up{job="orchestrator"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Orchestrator is down"
        description: "Orchestrator has been down for more than 1 minute"
    
    - alert: OrchestratorHighErrorRate
      expr: rate(orchestrator_deployment_errors_total[5m]) > 0.1
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High deployment error rate"
        description: "Orchestrator deployment error rate is above 10% for 2 minutes"
    
    - alert: OrchestratorHighLatency
      expr: histogram_quantile(0.95, rate(orchestrator_deployment_duration_seconds_bucket[5m])) > 300
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High deployment latency"
        description: "95th percentile deployment duration is above 5 minutes"
    
    - alert: OrchestratorFrequentRollbacks
      expr: rate(orchestrator_rollbacks_total[1h]) > 0.05
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "Frequent rollbacks detected"
        description: "Rollback rate is above 5% per hour"